theme: modernist
title: syscall
author: BitQuarky
description: all things (and thoughts) computer or hobby. primarily low level quarks and explanations of different computer behaviors as I discover them.
